baseurl = "http://mediathread.info/"
languageCode = "en-us"
title = "Mediathread Info"
metaDataFormat = "yaml"
[[menu.main]]
  name = "home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "about"
  weight = 2
  identifier = "about"
  url = "#"

[[menu.main]]
  name = "get started"
  weight = 3
  identifier = "get started"
  url = "#"

[[menu.main]]
  name = "Sign in @ Columbia"
  parent = "get started"
  weight = 1
  identifier = "sign in at columbia"
  url = "https://mediathread.ccnmtl.columbia.edu/"

[[menu.main]]
  name = "get involved"
  weight = 4
  identifier = "get involved"
  url = "#"

[[menu.main]]
  name = "faq"
  weight = 5
  identifier = "faq"
  url = "/faq"
